export const catalogProducts = [
  { id: '00001',
    name: 'Producto Ejemplo 1',
    price: 9990,
  },
  { id: '00002',
    name: 'Producto Ejemplo 2',
    price: 5990,
  },
  { id: '00003',
    name: 'Producto Ejemplo 3',
    price: 17990,
  },
  { id: '00004',
    name: 'Producto Ejemplo 4',
    price: 13990,
  },
  { id: '00005',
    name: 'Producto Ejemplo 5',
    price: 25590,
  },
  // { id: '00006',
  //   name: 'Producto Ejemplo 6',
  //   price: 23990,
  // },

];

export const postedRequests = [
  { id: '10001',
    status: 'start',
    name: 'Desarrollador',
    vacancies: 3,
    jobDuration: '3 meses',
    descriptionSummary: 'Desarrollador Java, Python y Ruby',
    createdDate: new Date('05/30/2020'),
    postedDate: new Date('10/30/2020'),
    SLA: new Date('10/30/2021'),
    jobDescription: 'Se busca desarrolador para mantener las API de la empresa X, que ..+ Lorem ipsum' +
    'dolor sit amet consectetur adipisicing elit. Consequuntur, ea? ',
  },
  { id: '10002',
    status: 'on-going',
    name: 'Administrador de sistemas war',
    vacancies: 2,
    jobDuration: '2 meses',
    descriptionSummary: 'Lorem ipsum dolor sit amet.',
    createdDate: new Date('10/30/2020'),
    postedDate: new Date('11/30/2020'),
    SLA: new Date('05/22/2021'),
    jobDescription: 'Lorem ipsum dolor sit amet consectetur adipisicing elit. Animi, natus nobis dolor' +
    'vel quod quos vitae soluta modi odit quo.',
  },
  { id: '10003',
    status: 'ready',
    name: 'Analista',
    vacancies: 4,
    jobDuration: '3 meses',
    descriptionSummary: 'Lorem ipsum dolor sit amet consectetur.',
    createdDate: new Date('01/25/2020'),
    postedDate: new Date('01/30/2020'),
    SLA: new Date('05/23/2021'),
    jobDescription: 'Se busca desarrolador para mantener las API de la empresa X, que ..+ Lorem ipsum' +
    'dolor sit amet consectetur adipisicing elit. Consequuntur, ea? ',
  },
  { id: '10004',
    status: 'start',
    name: 'Ingeniero en Datos',
    vacancies: 1,
    jobDuration: '1 mes',
    descriptionSummary: 'Desarrollador Java, Python y Ruby',
    createdDate: new Date('11/30/2020'),
    postedDate: new Date('11/15/2020'),
    SLA: new Date('05/10/2021'),
    jobDescription: 'Se busca desarrolador para mantener las API de la empresa X, que ..+ Lorem ipsum' +
    'dolor sit amet consectetur adipisicing elit. Consequuntur, ea? ',
  },
  { id: '10005',
    status: 'ready',
    name: 'Data Scientist',
    vacancies: 6,
    jobDuration: '2 meses',
    descriptionSummary: 'Desarrollador Java, Python y Ruby',
    createdDate: new Date('11/30/2020'),
    postedDate: new Date('01/10/2021'),
    SLA: new Date('05/30/2021'),
    jobDescription: 'Se busca desarrolador para mantener las API de la empresa X, que ..+ Lorem ipsum' +
    'dolor sit amet consectetur adipisicing elit. Consequuntur, ea? ',
  },
  { id: '10006',
    status: 'on-going',
    name: 'BI Engineer',
    vacancies: 2,
    jobDuration: '1 mes',
    descriptionSummary: 'Desarrollador Java, Python y Ruby',
    createdDate: new Date('01/30/2020'),
    postedDate: new Date('02/15/2021'),
    SLA: new Date('05/25/2021'),
    jobDescription: 'Se busca desarrolador para mantener las API de la empresa X, que ..+ Lorem ipsum' +
    'dolor sit amet consectetur adipisicing elit. Consequuntur, ea? ',
  },

];
